/*
 You need to use the classicmodels database.

1. For every product in the order details table get the product code and calculate subtotal (quantity * price)
 for every product order where quantity is greater than 20 and price is less than 120.
 Round subtotal on two decimal places.
 */

 USE classicmodels;

SELECT p.productCode,
       ROUND(SUM(od.quantityOrdered * od.priceEach), 2) AS Subtotal
FROM products p
JOIN orderdetails od
ON p.productCode = od.productCode
WHERE od.quantityOrdered > 20 AND od.priceEach < 120
GROUP BY p.productCode
ORDER BY p.productCode;

/*
2. Calculate the total sales (quantityOrdered * priceEach) for each employee, including the employee's
 full name and total sales amount. Only include employees who have managed sales above 150,000.
 */
SELECT e.firstName, e.lastName,
       SUM(od.quantityOrdered * od.priceEach) AS totalSales
FROM employees e
JOIN customers c
ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders o
ON c.customerNumber = o.customerNumber
JOIN orderdetails od
ON o.orderNumber = od.orderNumber
GROUP BY e.employeeNumber, e.firstName, e.lastName
HAVING totalSales > 150000
ORDER BY totalSales DESC ;

/*
3. For each product line, calculate the total number of orders and the total quantity ordered.
 Include only product lines with more than 200 orders.
 */
SELECT p.productLine,
       COUNT(DISTINCT od.orderNumber) AS totalOrders,
       SUM(od.quantityOrdered) AS totalQuantity
FROM products p
JOIN orderdetails od
ON p.productCode = od.productCode
GROUP BY p.productLine
HAVING totalOrders > 200;

/*
4. Find the total sales (quantityOrdered * priceEach) for each product, along with the product name
and product line, and include only products with total sales above 50,000.
 */

SELECT p.productName,
       p.productLine,
       SUM(od.quantityOrdered * od.priceEach) AS totalSales
FROM products p
JOIN orderdetails od
ON p.productCode = od.productCode
GROUP BY p.productCode
HAVING totalSales > 50000
ORDER BY totalSales DESC;

/*
5. Get the maximum, minimum, total, and average credit limit for all customers in each country and
each city where the country and city are not null. Order the result set by country in
descending order and by city in ascending order.
 */
SELECT
    MAX(creditLimit) AS "Max credit limit",
    MIN(creditLimit) AS "Min credit limit",
    SUM(creditLimit) AS "Total credit limit",
    AVG(creditLimit) AS "Avg credit limit"
FROM customers
WHERE country IS NOT NULL
AND
city IS NOT NULL
GROUP BY country, city
ORDER BY country DESC, city ASC;

/*
You need to use the Sakila database.

6. Write a query to count the number of films per rating for an actor Jennifer Davis.
Only include ratings where the actor has appeared in at least 5 films.
 */

USE sakila;
SELECT
    f.rating AS "Film rating",
    COUNT(f.film_id) AS "Number of films"
FROM film f
JOIN film_actor fa
ON f.film_id = fa.film_id
JOIN actor a
ON fa.actor_id = a.actor_id
WHERE a.first_name = 'Jennifer' AND a.last_name = 'Davis'
GROUP BY f.rating
HAVING COUNT(f.film_id) >= 5;

/*
7. Write a query to calculate the total revenue collected from rentals for each city.
Only include cities with a total revenue greater than $190. Order result set by total_revenue
in descending order.
 */
SELECT
    SUM(p.amount) AS "Total revenue",
    ci.city
FROM city ci
JOIN address a
ON ci.city_id = a.city_id
JOIN customer c
ON a.address_id = c.address_id
JOIN rental r
ON c.customer_id = r.customer_id
JOIN payment p
ON r.rental_id = p.rental_id
GROUP BY ci.city
HAVING SUM(p.amount) > 190
ORDER BY SUM(p.amount) DESC;

/*
8. Find the total revenue generated by each film category and the total number of rentals.
Only include categories where the total revenue exceeds $1000.
 */
SELECT
    c.name AS categoryName,
    SUM(p.amount) AS totalRevenue,
    COUNT(r.rental_id) AS totalRentals
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY c.category_id
HAVING totalRevenue > 1000
ORDER BY totalRevenue DESC;

/*
You need to use the Employees database.

9. Calculate the total number of employees for each department. Order the result set by descending order.
*/
 USE employees;
SELECT d.dept_name, COUNT(de.emp_no) AS "Number of employees"
FROM departments d
JOIN dept_emp de ON d.dept_no = de.dept_no
GROUP BY d.dept_no
ORDER BY COUNT(de.emp_no) DESC;

/*
10. Write a query to identify the employee who has been in each department the longest.
Include the employee’s first name, last name, department name, and the duration of service in days.
 */
SELECT
    d.dept_name,
    e.first_name,
    e.last_name,
    DATEDIFF(de.to_date, de.from_date) AS duration_days #OR DATEDIFF(MAX(de.to_date), MIN(de.from_date)) AS duration_days
FROM departments d
JOIN dept_emp de ON d.dept_no = de.dept_no
JOIN employees.employees e ON de.emp_no = e.emp_no
GROUP BY d.dept_no, e.emp_no
ORDER BY d.dept_name ASC, duration_days DESC;

/*
11. Find the total salary expenditure for each department, along with the department name.
Only include departments with a total salary expenditure exceeding $5,000,000.
 */
SELECT
    d.dept_name,
    SUM(s.salary) AS totalExpediture
FROM departments d
JOIN dept_emp de ON d.dept_no = de.dept_no
JOIN employees e ON de.emp_no = e.emp_no
JOIN salaries s ON e.emp_no = s.emp_no
GROUP BY d.dept_no
HAVING totalExpediture > 5000000
ORDER BY totalExpediture DESC;

/*
12. For each job title, calculate the total number of employees and the average salary.
Include only titles with more than 1,000 employees.
 */
SELECT
    t.title,
    COUNT(e.emp_no) AS totalEmmployees,
    AVG(s.salary) AS avgSalary
FROM titles t
JOIN employees e ON t.emp_no = e.emp_no
JOIN salaries s ON e.emp_no = s.emp_no
GROUP BY t.title
HAVING totalEmmployees > 1000
ORDER BY totalEmmployees DESC;

/*
13. Find the longest tenure (in days) of employees for each department, along with the department name.
Include only departments where the longest tenure exceeds 5,000 days. Tenure refers to the
number of days an employee worked.
 */
SELECT
    d.dept_name,
    MAX(DATEDIFF(de.to_date, de.from_date)) AS longestTenure
FROM departments d
JOIN dept_emp de ON d.dept_no = de.dept_no
GROUP BY d.dept_no
HAVING longestTenure > 5000
ORDER BY d.dept_name;

/*
14. Write a query to create a JSON array of employee details for each department.
The JSON object in the array should include the employee’s firstName, lastName, title, hireDate, and salary.
Only include employees whose last names contain the letter "x".
Display the department name and the JSON array of employee details for each department.
 */
SELECT
    d.dept_name AS departmentName,
    JSON_ARRAYAGG(
        JSON_OBJECT(
            'title', t.title,
            'salary', s.salary,
            'hireDAte', e.hire_date,
            'lastName', e.last_name,
            'firstName', e.first_name
        )
    ) AS employeeDetails
FROM titles t
JOIN employees e ON t.emp_no = e.emp_no
JOIN salaries s ON e.emp_no = s.emp_no
JOIN dept_emp de ON e.emp_no = de.emp_no
JOIN departments d ON de.dept_no = d.dept_no
WHERE e.last_name LIKE '%x%'
GROUP BY d.dept_no, d.dept_name;

/*
You need to use the classicmodels database.

15. Write a query that will count how many orders were created starting from October 10th,
2003, and September 9th, 2004 for each status.
 */
USE classicmodels;
SELECT
    COUNT(orderNumber) AS "Number of created orders",
    status
FROM orders
WHERE orderDate BETWEEN '2003-10-10' AND '2004-09-09'
GROUP BY status;

/*
16. Get the product code, orderLineNumber, and average priceEach for every product and every
orderLineNumber where max priceEach is greater than 100. Order the result set by product code
in descending order.
 */
SELECT
    productCode,
    orderLineNumber,
    AVG(priceEach) AS "Average price each"
FROM orderdetails
GROUP BY productCode, orderLineNumber
HAVING MAX(priceEach) > 100
ORDER BY productCode DESC;

/*
17. Calculate the total revenue for each customer, showing the customer's name,
total revenue (quantityOrdered * priceEach), and the number of orders they placed.
Include only customers with total revenue exceeding $50,000.
 */
SELECT
    c.customerName,
    SUM(od.quantityOrdered * od.priceEach) AS totalRevenue,
    COUNT(o.orderNumber) AS numberOfOrders
FROM customers c
JOIN orders o ON c.customerNumber = o.customerNumber
JOIN orderdetails od ON o.orderNumber = od.orderNumber
GROUP BY c.customerNumber
HAVING totalRevenue > 50000
ORDER BY totalRevenue DESC;

/*
18. For each employee, find the total number of customers they manage and the total sales
generated by those customers. Include only employees managing more than 5 customers.
 */
SELECT
    e.firstName,
    e.lastName,
    COUNT(DISTINCT c.customerNumber) AS totalCustomers,
    SUM(p.amount) AS totalSales
FROM employees e
JOIN customers c ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN payments p ON c.customerNumber = p.customerNumber
GROUP BY e.employeeNumber, e.firstName, e.lastName
HAVING totalCustomers > 5
ORDER BY totalSales DESC;

/*
You need to use the sakila database.

19. Write a query to find the average rental rate of films in each category.
Only include categories where the average rental rate is higher than 3.00.
 */
USE sakila;

SELECT
    c.name AS "Category name",
    AVG(f.rental_rate) AS "Avg rental rate"
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.category_id
HAVING AVG(f.rental_rate) > 3.00
ORDER BY c.name;

/*
20. Write a query to calculate the average rental duration of films for each city.
Include only those cities where the average rental duration is greater than 4 days.
 */
SELECT
    ci.city AS "City name",
    AVG(f.rental_duration) AS "Average retal duration"
FROM city ci
JOIN address a ON ci.city_id = a.city_id
JOIN store s ON a.address_id = s.address_id
JOIN inventory i ON s.store_id = i.store_id
JOIN film f ON i.film_id = f.film_id
GROUP BY ci.city_id
HAVING AVG(f.rental_duration) > 4

/*
21. Find the total revenue generated by each actor, showing their full name and the total number
of films they appeared in. Include only actors who have generated more than $2,000 in revenue.

 */

SELECT
    a.first_name,
    a.last_name,
    SUM(p.amount) AS totalRevenue,
    COUNT(DISTINCT f.film_id) AS totalFilms
FROM actor a
JOIN film_actor fa ON a.actor_id = fa.actor_id
JOIN film  f ON fa.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY a.actor_id
HAVING totalRevenue > 2000
ORDER BY totalRevenue DESC

/*
22. Calculate the average rental duration for films in each category, showing the category name
and the average duration. Include only categories where the average rental duration exceeds 5 days.
 */
SELECT
    c.name AS categoryName,
    AVG(f.rental_duration) AS avgRentalDuration
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.category_id
HAVING avgRentalDuration > 5
ORDER BY avgRentalDuration DESC;

/*
23. For each city, find the total number of rentals and the total revenue generated.
Include only cities with more than 25 rentals.
 */
SELECT
    ci.city,
    COUNT(r.rental_id) AS totalRentals,
    SUM(p.amount) AS totalRevenue
FROM city ci
JOIN address a ON ci.city_id = a.city_id
JOIN customer c ON a.address_id = c.address_id
JOIN rental r ON c.customer_id = r.customer_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY ci.city_id
HAVING totalRentals > 25
ORDER BY totalRevenue DESC;

/*
You need to use the employees database.

24. Write a query to calculate the maximum and minimum salary for each employee.
 */
USE employees;

SELECT
    e.first_name,
    e.last_name,
    e.emp_no,
    MAX(s.salary) AS "Max salary",
    MIN(s.salary) AS "Min salary"
FROM employees e
JOIN salaries s ON e.emp_no = s.emp_no
GROUP BY e.emp_no;

/*
25. Calculate the average salary for each job title over time.
Include the title and average salary, and present the results ordered by the title alphabetically.
 */
SELECT
    t.title,
    AVG(s.salary) AS average_salary
FROM titles t
JOIN employees e ON t.emp_no = e.emp_no
JOIN salaries s ON e.emp_no = s.emp_no
GROUP BY t.title
ORDER BY t.title;

/*
26. Generate a JSON array for each department containing the names of employees and their job titles.
 */
SELECT
    d.dept_name AS departmentName,
    JSON_ARRAYAGG(
        JSON_OBJECT(
            'title', t.title,
            'lastName', e.last_name,
            'firstName', e.first_name
        )
    ) AS employeeTitles
FROM departments d
JOIN dept_emp de ON d.dept_no = de.dept_no
JOIN employees e ON de.emp_no = e.emp_no
JOIN titles t ON e.emp_no = t.emp_no
GROUP BY d.dept_no

/*
27.  Find the employee ID, first name, and last name of employees who have worked in multiple departments.
 */
SELECT
    e.emp_no,
    e.first_name,
    e.last_name
FROM employees e
JOIN dept_emp de ON e.emp_no = de.emp_no
GROUP BY e.emp_no
HAVING COUNT(de.dept_no) > 1;

/*
28. List employees who have only ever had salaries within the range
of $70,000 to $80,000 and whose first name ends with ‘r’.
 */
SELECT DISTINCT
    e.emp_no,
    e.first_name,
    e.last_name
FROM employees e
JOIN salaries s ON e.emp_no = s.emp_no
WHERE e.first_name LIKE '%r'
GROUP BY e.emp_no
HAVING MIN(s.salary) >= 70000 AND MAX(s.salary) <= 80000;