/*
 1. Retrieve the rental ID, rental date, days since the rental, return status,
 and customer name for all rentals. Calculate the days since the rental date
 using the current date. Determine the return status as 'Overdue' if the
 rental period (difference between return date and rental date)
 exceeds 3 days; otherwise, mark it as 'OnTime.' Format the customer name by
 concatenating the first and last names, converting it to uppercase, padding
 it to 30 characters with asterisks, and replacing null values with 'UNKNOWN.'
 Order the result set by days since the rental in descending order.
 */

 USE sakila;

SELECT
    r.rental_id,
    r.rental_date,
    DATEDIFF(curdate(), r.rental_date) AS days_since_the_rental,
    IF(DATEDIFF(r.return_date, r.rental_date) > 3, 'Overdue', 'OnTime') AS return_status,
    CONCAT(
            IFNULL(UPPER(c.first_name), 'UNKNOWN'),
            ' ',
            IFNULL(UPPER(c.last_name), 'UNKNOWN'),
            REPEAT(
                    '*',
                    30 - CHAR_LENGTH(CONCAT(
                            IFNULL(UPPER(c.first_name), 'UNKNOWN'),
                            ' ',
                            IFNULL(UPPER(c.last_name), 'UNKNOWN')
                            )
                    )
            )
    ) AS customer_name
FROM rental r
JOIN customer c ON r.customer_id = c.customer_id
ORDER BY days_since_the_rental DESC;

/*
 2. Retrieve the film ID, a fancy title (film title generated by reversing
 the first five characters of the title in uppercase and appending the rest
 of the title in lowercase), description length, average payment amount
 rounded to 2 decimal points, total unique customers who rented the film,
 bit status of the film ID ('BITTY' if the binary representation of the film
 ID has more than 4 set bits, otherwise 'NOT BITTY.'), and cost category for
 films rented by more than 5 customers. Classify the cost category of the
 film as 'ABOVE AVG COST' if its replacement cost is greater than the average
 replacement cost of all films, otherwise 'BELOW AVG COST.' Order the result
 set by average payment in descending order, by the fancy title alphabetically.
 */

SELECT
    f.film_id,
    CONCAT(
            REVERSE(UPPER(SUBSTRING(f.title, 1, 5))),
            LOWER(SUBSTRING(f.title, 6, LENGTH(f.title) - 5))
    ) AS fancy_title,
    LENGTH(f.description) AS description_length,
    ROUND(AVG(p.amount), 2) AS average_payment_amount,
    COUNT(DISTINCT r.customer_id) AS no_unique_customers,
    IF(BIT_COUNT(f.film_id) > 4, 'BITTY', 'NOT BITTY') AS bit_status,
    IF(
            f.replacement_cost > (
                SELECT AVG(replacement_cost) FROM film
            ),
            'ABOVE AVG COST',
            'BELOW AVG COOST'
    ) AS cost_category
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY f.film_id
HAVING COUNT(r.customer_id) > 5
ORDER BY average_payment_amount DESC, fancy_title ASC;

/*
 3. Retrieve the film ID, total revenue, rental count, film title,
 a shortened version of the title (first 10 characters), and the price
 category for all films with total revenue exceeding $100 from payments
 made between 2004 and 2006. Classify films into price categories based
 on their rental rate: 'Premium' for rates $3.00 or higher, 'Standard'
 for rates between $2.00 and $2.99, and 'Budget' for rates below $2.00.
 Order the result set by the film title in ascending order.
 Solve the task using a derived table.
 */

 SELECT
    dt.film_id,
    dt.total_revenue,
    dt.rental_count,
    dt.title,
    LEFT(dt.title, 10) AS short_title,
    CASE
        WHEN dt.rental_rate >= 3 THEN 'Premium'
        WHEN dt.rental_rate >= 2 THEN 'Standard'
        ELSE 'Budget'
    END AS price_category
FROM (
    SELECT
        f.film_id,
        f.title,
        f.rental_rate,
        SUM(p.amount) AS total_revenue,
        COUNT(r.rental_id) AS rental_count
    FROM film f
    JOIN inventory i ON f.film_id = i.film_id
    JOIN rental r ON i.inventory_id = r.inventory_id
    JOIN payment p ON r.rental_id = p.rental_id
    WHERE YEAR(p.payment_date) BETWEEN 2004 AND 2006
    GROUP BY f.film_id, f.title, f.rental_rate
) dt
WHERE dt.total_revenue > 100
ORDER BY dt.title;

/*
 4. Retrieve the order number, order date, days since the order was placed,
 shipping status, and customer name for all orders. Calculate the number
 of days since the order date, and mark the shipping status as 'Overdue'
 if the shipping duration exceeds 3 days; otherwise, mark it as 'OnTime.'
 Customer names need to be in uppercase, padded them to 30 characters
 with asterisks, and replacing null values with 'UNKNOWN.' Order the result
 set by days since the order was placed in descending order.
 */
USE classicmodels;
SELECT
    o.orderNumber,
    o.orderDate,
    DATEDIFF(CURDATE(), o.orderDate) AS days_since_order,
    IF (DATEDIFF(o.shippedDate, o.orderDate) > 3, 'Overdue', 'OnTime') AS shipping_status,
    CONCAT(
        REPEAT('*',
            30 - CHAR_LENGTH(IFNULL(UPPER(c.customerName), 'UNKNOWN'))
        ),
        IFNULL(UPPER(c.customerName), 'UNKNOWN')
    ) AS customer_name
FROM orders o
LEFT JOIN customers c ON o.customerNumber = c.customerNumber
ORDER BY days_since_order DESC;

/*
 5. Retrieve the customer ID, the customer name in lowercase, the first 5 characters
 of the customer name reversed, the total number of orders, and count of overdue orders
 for all customers with more than two overdue orders. Overdue orders are defined as
 those placed over 30 days ago. Additionally, format the customer's phone number by
 extracting the country code if it starts with a '+', or label it as "Bad format" otherwise.
 Determine the customer's bit status as 'HIGH-BIT' if the bit count of their ID exceeds 5, or
 'LOW-BIT' otherwise. Order the result set by the number of overdue orders in descending order.
 */
SELECT
    c.customerNumber,
    LOWER(c.customerName) AS customer_name,
    REVERSE(LEFT(c.customerName, 5)) AS reversed_name,
    COUNT(o.orderNumber) AS total_orders,
    SUM(
        CASE
            WHEN DATEDIFF(CURDATE(), o.orderDate) > 30 THEN 1
            ELSE 0
        END
    ) AS overdue_orders,
    CASE
        WHEN c.phone LIKE '+%' THEN SUBSTRING_INDEX(c.phone, ' ', 1)
        ELSE 'Bad format'
    END AS phone_format,
    CASE
        WHEN BIT_COUNT(c.customerNumber) > 5 THEN 'HIGH-BIT'
        ELSE 'LOW-BIT'
    END AS bit_status
FROM customers c
JOIN orders o ON c.customerNumber = o.customerNumber
GROUP BY c.customerNumber, c.customerName, c.phone
HAVING overdue_orders > 2
ORDER BY overdue_orders DESC;

-- select * from customers;

/*
 6. Retrieve the total sales amount (salesorderheader table) for each product
 category and sales reason for sales made on or after May 30th, 2011. Only include
 sales that are associated with products that had a special offer applied.
 Include only product categories with total sales greater than $100,000.
 Order the result set by total sales amount in descending order.
 */

USE adventureworks;
SELECT
    pc.Name AS product_category,
    sr.Name AS sales_reason,
    SUM(soh.TotalDue) AS total_sales
FROM sales_salesorderheader soh
JOIN sales_salesorderdetail sod ON soh.SalesOrderID = sod.SalesOrderID
JOIN production_product p ON sod.ProductID = p.ProductID
JOIN production_productsubcategory psc ON p.ProductSubcategoryID = psc.ProductSubcategoryID
JOIN production_productcategory pc ON psc.ProductCategoryID = pc.ProductCategoryID
JOIN sales_specialofferproduct sop ON p.ProductID = sop.ProductID
JOIN sales_salesorderheadersalesreason sohsr ON soh.SalesOrderID = sohsr.SalesOrderID
JOIN sales_salesreason sr ON sohsr.SalesReasonID = sr.SalesReasonID
WHERE soh.OrderDate >= '2011-05-30'
GROUP BY pc.Name, sr.Name
HAVING SUM(soh.TotalDue) > 100000
ORDER BY total_sales DESC;

/*
 7. Retrieve the product ID, total sales amount, number of sales lines, product name,
 a shortened version of the product name (first 10 characters), and the price
 category for all products sold in 2013 with total sales exceeding $50,000. Classify products
 into price categories based on their list price: 'High-End' for prices $1000 or more,
 'Mid-Range' for prices between $500 and $999, and 'Budget' for prices below $500.
 Order the results by total sales amount in descending order. Solve the task using a derived table.
 */

SELECT
    dt.ProductID,
    dt.total_sales,
    dt.sales_lines,
    dt.Name,
    LEFT(dt.Name, 10) AS short_name,
    CASE
        WHEN dt.ListPrice >= 1000 THEN 'High-End'
        WHEN dt.ListPrice >= 500 THEN 'Mid-Range'
        ELSE 'Budget'
    END AS price_category
FROM (
    SELECT
        p.ProductID,
        p.Name,
        p.ListPrice,
        SUM(sod.LineTotal) AS total_sales,
        COUNT(*) AS sales_lines
    FROM sales_salesorderdetail sod
    JOIN sales_salesorderheader soh ON sod.SalesOrderID = soh.SalesOrderID
    JOIN production_product p ON sod.ProductID = p.ProductID
    WHERE YEAR(soh.OrderDate) = 2013
    GROUP BY p.ProductID, p.Name, p.ListPrice
) dt
WHERE dt.total_sales > 50000
ORDER BY total_sales DESC;


/*
 8. Retrieve the product ID, product name (or 'No Name' if the name is missing),
 the first 10 characters of the product name, the year the product was first sold,
 and the release category for all products with total sales exceeding $50,000 in 2013.
 Classify products into release categories based on the year they were first sold:
 'Legacy' for products introduced in 2011 or earlier, 'Mid-Lifecycle'
 for those introduced in 2012, and 'New Release' for those introduced in 2013 or later.
 Order the result set alphabetically by product name.
 */
SELECT
    p.ProductID,
    IFNULL(p.Name, 'No Name') AS product_name,
    LEFT(IFNULL(p.Name, 'No Name'), 10) AS short_name,
    YEAR(MIN(soh.OrderDate)) AS first_sold_year,
    CASE
        WHEN YEAR(MIN(soh.OrderDate)) <= 2011 THEN 'Legacy'
        WHEN YEAR(MIN(soh.OrderDate)) = 2012 THEN 'Mid-Lifecycle'
        ELSE 'New Release'
    END AS release_category
FROM sales_salesorderdetail sod
JOIN sales_salesorderheader soh ON sod.SalesOrderID = soh.SalesOrderID
JOIN production_product p ON sod.ProductID = p.ProductID
WHERE YEAR(soh.OrderDate) = 2013
GROUP BY p.ProductID, p.Name
HAVING SUM(sod.LineTotal) > 50000
ORDER BY product_name;

/*
 9. Retrieve the sales order ID, order number (formatted as 'SO-[SalesOrderID]'),
 the number of days since the start of the calendar (using the TO_DAYS function),
 the order year, freight cost (with NULL values replaced by 0), total due amount,
 and a running total of the total due. The running total is calculated in order of
 the sales order date, including all prior rows up to the current one. Order the
 result set by the sales order date.
 */
SELECT
    SalesOrderID,
    CONCAT('SO-', SalesOrderID) AS order_number,
    TO_DAYS(OrderDate) AS days_since_calendar_start,
    YEAR(OrderDate) AS order_year,
    IFNULL(Freight, 0) AS freight,
    TotalDue,
    SUM(TotalDue) OVER (
        ORDER BY OrderDate
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_total
FROM sales_salesorderheader
ORDER BY OrderDate;

/*
 10. Retrieve all departments (present ID and name) with the average and maximum
 sick leave hours of their employees. Only include departments with more than
 10 employees and whose job titles have more than 5 characters.
 Order the results by the average sick leave hours in descending order.
 */

SELECT
    d.DepartmentID,
    d.Name,
    AVG(e.SickLeaveHours) AS avg_sick_leave,
    MAX(e.SickLeaveHours) AS max_sick_leave
FROM humanresources_department d
JOIN humanresources_employeedepartmenthistory edh ON d.DepartmentID = edh.DepartmentID
JOIN humanresources_employee e ON edh.BusinessEntityID = e.BusinessEntityID
WHERE LENGTH(e.JobTitle) > 5
GROUP BY d.DepartmentID, d.Name
HAVING COUNT(*) > 10
ORDER BY avg_sick_leave DESC;

